channels:
- conda-forge
dependencies:
- python=3.13.2
- pip<=25.1.1
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - numpy==2.2.4
  - pandas==2.3.3
  - scikit-learn==1.7.0
  - scipy==1.16.0
name: mlflow-env
